meta_product_name: "Mood Wizard"
meta_title: "Mood Wizard - Track your mood, be happy 🙂"
meta_description: "Mood Wizard helps keep track of your mood and recommends activities and media based on how you are feeling--to help you get that 'me time' in your busy life."
meta_image: "cover.jpg" # should exist in `app/assets/images/`
